create table users
(
    id         number generated by default on null as identity primary key,
    username   varchar2(50) unique not null,
    password   varchar2(255) not null,
    email      varchar2(100) unique not null,
    full_name  varchar2(100),
    role_id    number not null,
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp on update current_timestamp,
    constraint fk_role foreign key (role_id) references roles (id)
);
