create table content
(
    id          number generated by default on null as identity primary key,
    title       varchar2(255) not null,
    slug        varchar2(255) unique not null,
    body        clob   not null,
    excerpt     clob,
    status      varchar2(20) check (status in ('draft', 'published', 'archived')),
    author_id   number not null,
    category_id number not null,
    created_at  timestamp default current_timestamp,
    updated_at  timestamp default current_timestamp on update current_timestamp,
    constraint fk_content_author foreign key (author_id) references users (id),
    constraint fk_content_category foreign key (category_id) references categories (id)
);