create table media
(
    id          number generated by default on null as identity primary key,
    file_name   varchar2(255) not null,
    file_type   varchar2(50),
    file_size   number,
    url         varchar2(255) not null,
    uploaded_by number not null,
    uploaded_at timestamp default current_timestamp,
    constraint fk_media_user foreign key (uploaded_by) references users (id)
);