create table comments
(
    id         number generated by default on null as identity primary key,
    content_id number not null,
    author_id  number not null,
    body       clob   not null,
    status     varchar2(20) check (status in ('pending', 'approved', 'rejected')),
    created_at timestamp default current_timestamp,
    updated_at timestamp default current_timestamp on update current_timestamp,
    constraint fk_comments_content foreign key (content_id) references content (id),
    constraint fk_comments_author foreign key (author_id) references users (id)
);