create table audit_logs
(
    id         number generated by default on null as identity primary key,
    action     varchar2(100) not null,
    user_id    number not null,
    table_name varchar2(100),
    record_id  number,
    timestamp  timestamp default current_timestamp,
    constraint fk_audit_logs_user foreign key (user_id) references users (id)
);